### ISSUE TITLE
NPE when using LocalDynamoDbRule 

### ISSUE THREAD

**Issue by mlk** [mlk/AssortmentOfJUnitRules#2]
https://gist.github.com/scho/3101c83488e61d32234ce79c5db6ac06

**Comment by mlk** [comment]
I ran into an issue with this. I get a NPE in LocalDynamoDbRule.java:38 (DynamoDBEmbedded.create() returns null). Before that, the native SQLite part logs: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: com.almworks.sqlite4java.SQLiteException: [-91] sqlite4java cannot find native library. I use com.github.mlk:DynamoDBLocal:1.11.119 and com.github.mlk:assortmentofjunitrules:1.5.39. Shouldn't the LocalDynamoDbRule take care of all the native SQLite stuff? – scho yesterday

**Comment by mlk** [comment]
Been able to replicated locally with a minimal POM file. The issue does not affect Gradle at this time.

**Comment by ghost** [comment]
2018-08-12 11:45:24.197  INFO 1827 --- [tp1855589354-31] c.a.s.d.l.s.LocalDynamoDBServerHandler   : accessKey: aewfw	us-east-1
2018-08-12 11:45:24.198  INFO 1827 --- [tp1855589354-31] c.a.s.d.l.s.LocalDynamoDBServerHandler   : target: CreateTable
2018-08-12 11:45:24.205  WARN 1827 --- [  SQLiteQueue[]] com.almworks.sqlite4java                 : [sqlite] cannot open DB[11]: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: com.almworks.sqlite4java.SQLiteException: [-91] sqlite4java cannot find native library
2018-08-12 11:45:24.206 ERROR 1827 --- [  SQLiteQueue[]] com.almworks.sqlite4java                 : [sqlite] SQLiteQueue[]: error running job queue

com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: com.almworks.sqlite4java.SQLiteException: [-91] sqlite4java cannot find native library
	at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:97)
	at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1441)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:293)
	at com.almworks.sqlite4java.SQLiteQueue.openConnection(SQLiteQueue.java:464)
	at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:641)
	at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
	at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
	at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.almworks.sqlite4java.SQLiteException: [-91] sqlite4java cannot find native library
	at com.almworks.sqlite4java.Internal.loadLibraryX(Internal.java:136)
	at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:95)
	... 9 common frames omitted

**Comment by mlk** [comment]
Thanks YunchengLiao. Are you using Maven?

**Comment by ghost** [comment]
Actually, I figured this out.

What I did is copy dependencies in native-lib, then set the system property to point Local Dynamodb to it.

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.1.1</version>
        <executions>
          <execution>
            <id>copy</id>
            <phase>compile</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <includeScope></includeScope>
              <includeTypes>so,dll,dylib</includeTypes>
              <outputDirectory>native-libs</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

```
    System.setProperty("sqlite4java.library.path", "native-libs");

```

**Comment by ghost** [comment]
I followed the steps here:

https://www.baeldung.com/dynamodb-local-integration-tests

**Comment by mlk** [comment]
The junit rule should handle this for you, but alas is not working in maven
(it does in gradle).

**Comment by deba10106** [comment]
This solution is not working. I don't know why! I followed the solution given above but still showing the exactly same error! I'm using gradle and is not working in gradle even!

**Comment by alejandro-poggi-offerup** [comment]
@deba10106 did you find a solution to this?

**Comment by JimMcKenzieSmith** [comment]
@alejandro-poggi-offerup Did you find a solution to this?
